<a href="https://colab.research.google.com/github/dimplehasinipalla/machine-learning-sem5/blob/main/5_8_Linearregression_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

data = pd.DataFrame({
    'Weight': [79, 69, 73, 95, 82, 55, 69, 71, 64, 69],
    'Height': [1.80, 1.68, 1.82, 1.70, 1.87, 1.55, 1.50, 1.78, 1.67, 1.64],
    'Age': [35, 39, 25, 60, 27, 18, 89, 42, 16, 52],
    'Gender': ['Male', 'Male', 'Male', 'Male', 'Male', 'Female', 'Female', 'Female', 'Female', 'Female']
})

data

   Weight  Height  Age  Gender
0      79    1.80   35    Male
1      69    1.68   39    Male
2      73    1.82   25    Male
3      95    1.70   60    Male
4      82    1.87   27    Male
5      55    1.55   18  Female
6      69    1.50   89  Female
7      71    1.78   42  Female
8      64    1.67   16  Female
9      69    1.64   52  Female

In [4]:
encoder = LabelEncoder()
data['Gender'] = encoder.fit_transform(data['Gender'])

data

   Weight  Height  Age  Gender
0      79    1.80   35       1
1      69    1.68   39       1
2      73    1.82   25       1
3      95    1.70   60       1
4      82    1.87   27       1
5      55    1.55   18       0
6      69    1.50   89       0
7      71    1.78   42       0
8      64    1.67   16       0
9      69    1.64   52       0

In [5]:
X = data[['Height', 'Age', 'Gender']]
y = data['Weight']

print("X:")
print(X)
print("\ny:")
print(y)

X:
   Height  Age  Gender
0    1.80   35       1
1    1.68   39       1
2    1.82   25       1
3    1.70   60       1
4    1.87   27       1
5    1.55   18       0
6    1.50   89       0
7    1.78   42       0
8    1.67   16       0
9    1.64   52       0

y:
0    79
1    69
2    73
3    95
4    82
5    55
6    69
7    71
8    64
9    69
Name: Weight, dtype: int64

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

X_train shape: (8, 3)
X_test shape: (2, 3)

In [7]:
model = LinearRegression()
model.fit(X_train, y_train)

print("Intercept (b0):", model.intercept_)
print("Coefficients (b1, b2, b3):", model.coef_)

Intercept (b0): -3.0552172392595196
Coefficients (b1, b2, b3): [32.8353363   0.31729474 14.62311848]

In [8]:
y_pred = model.predict(X_test)

print("Predicted values (y_pred):", y_pred)
print("Actual values (y_test):")
print(y_test)

Predicted values (y_pred): [56.85651025 79.10576115]
Actual values (y_test):
8    64
1    69
Name: Weight, dtype: int64

In [9]:
print("MAE =", mean_absolute_error(y_test, y_pred))
print("MSE =", mean_squared_error(y_test, y_pred))
print("RMSE =", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R2 =", r2_score(y_test, y_pred))

MAE = 8.624625451606978
MSE = 76.57792714844265
RMSE = 8.750881506936468
R2 = -11.252468343750825