<a href="https://colab.research.google.com/github/dimplehasinipalla/machine-learning-sem5/blob/main/Principal_Component_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

# Creating the dataset from Exercise 11.4 Question 2
data = {
    'Variable': ['Climate', 'Housing', 'Health', 'Crime', 'Transportation', 'Education', 'Arts', 'Recreation', 'Economy'],
    'PC1': [0.190, 0.544, 0.782, 0.365, 0.585, 0.394, 0.985, 0.520, 0.142],
    'PC2': [0.017, 0.020, -0.605, 0.294, 0.085, -0.273, 0.126, 0.402, 0.150],
    'PC3': [0.207, 0.204, 0.144, 0.585, 0.234, 0.027, 0.111, 0.519, 0.239]
}

df = pd.DataFrame(data)
df.set_index('Variable', inplace=True)
display(df)

                  PC1    PC2    PC3
Variable
Climate         0.190  0.017  0.207
Housing         0.544  0.020  0.204
Health          0.782 -0.605  0.144
Crime           0.365  0.294  0.585
Transportation  0.585  0.085  0.234
Education       0.394 -0.273  0.027
Arts            0.985  0.126  0.111
Recreation      0.520  0.402  0.519
Economy         0.142  0.150  0.239

In [2]:
# Calculate squared loadings to find the variance contribution of each variable per PC
squared_loadings = df ** 2

# Find the variable with the maximum squared loading for each principal component
principal_variables = squared_loadings.idxmax()

print("Principal Variable for each Principal Component (based on max squared loading):")
print(principal_variables)

display(squared_loadings)

Principal Variable for each Principal Component (based on max squared loading):
PC1      Arts
PC2    Health
PC3     Crime
dtype: object

                     PC1       PC2       PC3
Variable
Climate         0.036100  0.000289  0.042849
Housing         0.295936  0.000400  0.041616
Health          0.611524  0.366025  0.020736
Crime           0.133225  0.086436  0.342225
Transportation  0.342225  0.007225  0.054756
Education       0.155236  0.074529  0.000729
Arts            0.970225  0.015876  0.012321
Recreation      0.270400  0.161604  0.269361
Economy         0.020164  0.022500  0.057121

In [3]:
# Display the original component loadings table from the lab exercise
print("--- Exercise Table: Principal Component Loadings ---")
display(df)

# Find the maximum absolute loading for each variable across the components to see which PC it aligns with most strongly
max_pc_per_variable = df.abs().idxmax(axis=1)
print("\n--- Strongest Principal Component for Each Variable ---")
print(max_pc_per_variable)

# Overall dominant variable (highest loading overall)
dominant_variable = df.abs().stack().idxmax()
print(f"\nThe variable with the overall strongest loading is '{dominant_variable[0]}' on '{dominant_variable[1]}'")

--- Exercise Table: Principal Component Loadings ---

                  PC1    PC2    PC3
Variable
Climate         0.190  0.017  0.207
Housing         0.544  0.020  0.204
Health          0.782 -0.605  0.144
Crime           0.365  0.294  0.585
Transportation  0.585  0.085  0.234
Education       0.394 -0.273  0.027
Arts            0.985  0.126  0.111
Recreation      0.520  0.402  0.519
Economy         0.142  0.150  0.239

--- Strongest Principal Component for Each Variable ---
Variable
Climate           PC3
Housing           PC1
Health            PC1
Crime             PC3
Transportation    PC1
Education         PC1
Arts              PC1
Recreation        PC1
Economy           PC3
dtype: object

The variable with the overall strongest loading is 'Arts' on 'PC1'